function [NDat]=importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 15-Nov-2007 19:49:57

% Import the file
rawData1 = importdata(fileToRead1);

% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.
[unused,name] = fileparts(fileToRead1); %#ok
newData1.(genvarname(name)) = rawData1;

% Create new variables in the base workspace from those fields.
%I think this creates a generic global variable , I just want the data, and
%Ill make my own variable
%vars = fieldnames(newData1);
%for i = 1:length(vars)
%    assignin('caller', vars{i}, newData1.(vars{i}));
%end

NDat=newData1.(name);